
import java.awt.Font;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NAZAR ALWATTAR
 */
public class facultyInforUI extends javax.swing.JFrame {

    private ArrayList<ArrayList<String>> currentStudent;
    private ArrayList<ArrayList<String>> profPapers;
    public  BLPaper myPaper;
    public   BLFaculty bL;
     public Font font = new Font("CMonospaced", Font.BOLD,22);
     public Font font2 = new Font("CMonospaced", Font.BOLD,13);
    //public int paperIndex=1;
  // public boolean show =  true;
    
    /**
     * Creates new form facultyInforUI
     * @param ID
     */
    public facultyInforUI()
    {
    
    }
    public facultyInforUI(int ID) {
        
         bL = new BLFaculty(ID);
       
        try{
           
            bL.fetch();
         
                     
        }catch(DLException e)
        {
        //Do nothing
        
        }
       
        
       
                
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultyInfojPanel = new javax.swing.JPanel();
        facultyPapersjPanel = new javax.swing.JPanel();
        //Get papersList

        try {

            MySQLDatabase msdb = MySQLDatabase.getInstance();
            msdb.connect();
            bL.fetch();
            this.profPapers = bL.profPapersList();
        }
        catch(DLException e){
            //Do nothing
        }

        String[] profPapersTitle = new String[this.profPapers.size()+1];

        profPapersTitle[0] = "<click here to select paper>";
        for (int i=1;i<profPapersTitle.length;i++) {
            profPapersTitle[i] = this.profPapers.get(i-1).get(1);
            // System.out.println("This is the papers ID depends on the facultyID \n"+i +" "+this.profPapers.get(i-1).get(0));
            // System.out.println("This is the papers title depends on the facultyID \n" +i+" "+ profPapersTitle[i]);
        }
        facultypapersjComboBox = new javax.swing.JComboBox<>(profPapersTitle);
        facultyPapersComboboxjLabel = new javax.swing.JLabel();
        facultyPaperTitlejLabel = new javax.swing.JLabel();
        facultyPaperAbstractjLabel = new javax.swing.JLabel();
        facultyPaperCitationjLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        facultyPaperAbstractjTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        facultypaperTitlejTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        facultyPaperCitationjTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        try{
            bL.fetch();

        }catch(DLException e)
        {
            //Do nothing

        }
        facultynamejTextField = new javax.swing.JTextField(bL.firstName + " " + bL.lastName);
        facultyEmailjTextField = new javax.swing.JTextField(bL.email);
        //Current Studen(s) Name

        try {
            MySQLDatabase msdb = MySQLDatabase.getInstance();
            msdb.connect();

            this.currentStudent = bL.profCurrentStudentList();
        }
        catch(DLException e){
            //Do nothing
        }

        String[] profStudentNames = new String[this.currentStudent.size()+1];
        profStudentNames[0] = "";
        for (int i=1;i<profStudentNames.length;i++) {
            profStudentNames[i] = this.currentStudent.get(i-1).get(0);
            //  System.out.println("This is the Student(s) Name depends on the facultyID \n"+i+" "+profStudentNames[i]);

        }
        currentStudentjComboBox = new javax.swing.JComboBox<>(profStudentNames);
        currentStudentjLabel = new javax.swing.JLabel();
        lookingForstudentjLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lookingForStudentjjTextArea = new javax.swing.JTextArea(bL.askHelp);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        facultyInfojPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professor Information Page", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        facultyInfojPanel.setName(""); // NOI18N

        facultyPapersjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professor Papers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 15))); // NOI18N
        facultyPapersjPanel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        facultyPapersjPanel.setName("Professor Papers"); // NOI18N

        facultypapersjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(profPapersTitle));
        facultypapersjComboBox.setSelectedIndex(0);
        facultypapersjComboBox.setSelectedItem(facultypapersjComboBox);
        facultypapersjComboBox.setFont(font);
        facultypapersjComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                facultypapersjComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        facultyPapersComboboxjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        facultyPapersComboboxjLabel.setText("Papers");

        facultyPaperTitlejLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        facultyPaperTitlejLabel.setText("Title");

        facultyPaperAbstractjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        facultyPaperAbstractjLabel.setText("Abstract");

        facultyPaperCitationjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        facultyPaperCitationjLabel.setText("Citation");

        facultyPaperAbstractjTextArea.setEnabled(false);
        facultyPaperAbstractjTextArea.setColumns(20);
        facultyPaperAbstractjTextArea.setRows(5);
        jScrollPane3.setViewportView(facultyPaperAbstractjTextArea);

        facultypaperTitlejTextArea.setEnabled(false);
        facultypaperTitlejTextArea.setColumns(20);
        facultypaperTitlejTextArea.setRows(5);
        jScrollPane1.setViewportView(facultypaperTitlejTextArea);

        facultyPaperCitationjTextArea.setEnabled(false);
        facultyPaperCitationjTextArea.setColumns(20);
        facultyPaperCitationjTextArea.setRows(5);
        jScrollPane4.setViewportView(facultyPaperCitationjTextArea);

        javax.swing.GroupLayout facultyPapersjPanelLayout = new javax.swing.GroupLayout(facultyPapersjPanel);
        facultyPapersjPanel.setLayout(facultyPapersjPanelLayout);
        facultyPapersjPanelLayout.setHorizontalGroup(
            facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(facultyPaperAbstractjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(facultyPaperTitlejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(facultyPaperCitationjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(facultyPapersComboboxjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addComponent(facultypapersjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        facultyPapersjPanelLayout.setVerticalGroup(
            facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultypapersjComboBox)
                    .addComponent(facultyPapersComboboxjLabel))
                .addGap(17, 17, 17)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyPaperTitlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(facultyPaperAbstractjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyPapersjPanelLayout.createSequentialGroup()
                        .addComponent(facultyPaperCitationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Professor Name");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Professor Email");

        facultynamejTextField.setFont(font);

        facultyEmailjTextField.setFont(font);

        currentStudentjComboBox.setFont(font);
        currentStudentjComboBox.setSelectedIndex(1);
        currentStudentjComboBox.setSelectedItem(currentStudentjComboBox);

        currentStudentjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        currentStudentjLabel.setText("Current Student (s) Name");

        lookingForstudentjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lookingForstudentjLabel.setText("Looking for a student researcher in");

        lookingForStudentjjTextArea.setColumns(20);
        lookingForStudentjjTextArea.setRows(5);
        lookingForStudentjjTextArea.setFont(font2);
        jScrollPane2.setViewportView(lookingForStudentjjTextArea);
        if(lookingForStudentjjTextArea.getText().equals(""))
        lookingForStudentjjTextArea.setEnabled(false);
        else
        lookingForStudentjjTextArea.setEnabled(true);

        javax.swing.GroupLayout facultyInfojPanelLayout = new javax.swing.GroupLayout(facultyInfojPanel);
        facultyInfojPanel.setLayout(facultyInfojPanelLayout);
        facultyInfojPanelLayout.setHorizontalGroup(
            facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyInfojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                        .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentStudentjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lookingForstudentjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(currentStudentjComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 81, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facultyPapersjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facultyEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facultynamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        facultyInfojPanelLayout.setVerticalGroup(
            facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyInfojPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultynamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                        .addComponent(currentStudentjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(currentStudentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(lookingForstudentjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(facultyPapersjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(facultyInfojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(facultyInfojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        facultyInfojPanel.getAccessibleContext().setAccessibleName("Faculty Information Page");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void facultypapersjComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_facultypapersjComboBoxPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        
        
        
         if(facultypapersjComboBox.getSelectedIndex()>0)
        {
            
        int index = facultypapersjComboBox.getSelectedIndex();
           // System.out.println("Index  for this combobox element is "+ index);
            String item = facultypapersjComboBox.getSelectedItem().toString();
           // System.out.println("The Item  for this combobox element is "+ item);
            
            for(int i=0; i<profPapers.size(); i++)
            {
            if(profPapers.get(i).get(1).equals(item))
            {
          int  paperIndex =Integer.parseInt(profPapers.get(i).get(0));
              //  System.out.println("This is the paper id " + paperIndex);
                
                MySQLDatabase msdb = MySQLDatabase.getInstance();
                try {
                    msdb.connect();
                }catch(DLException e)
                {
//DO Nothing now
                }
               
              
                
                myPaper = new BLPaper(paperIndex);
                try {
                    myPaper.fetch();  
                    
                  //  show = true;
                    
                    facultypaperTitlejTextArea = new javax.swing.JTextArea(myPaper.title);
                    facultypaperTitlejTextArea.setColumns(20);
                    facultypaperTitlejTextArea.setRows(5);
                    facultypaperTitlejTextArea.setFont(font2);
                    jScrollPane1.setViewportView(facultypaperTitlejTextArea);
                   // System.out.println("This is the title for this paper " +  facultypaperTitlejTextField.getText());
                    facultyPaperAbstractjTextArea = new javax.swing.JTextArea(myPaper.pAbstract);
                   facultyPaperAbstractjTextArea.setColumns(20);
                   facultyPaperAbstractjTextArea.setRows(5);
                    facultyPaperAbstractjTextArea.setFont(font2);
                   jScrollPane3.setViewportView(facultyPaperAbstractjTextArea);
                   facultyPaperAbstractjTextArea.setLineWrap(true);
                   facultyPaperAbstractjTextArea.setWrapStyleWord(true);
                   facultyPaperCitationjTextArea = new javax.swing.JTextArea(myPaper.citation);
                    facultyPaperCitationjTextArea.setColumns(20);
                    facultyPaperCitationjTextArea.setRows(5);
                    facultyPaperCitationjTextArea.setFont(font2);
                    jScrollPane4.setViewportView(facultyPaperCitationjTextArea);
                    
                   
            
            }catch (DLException ex) {
             //Do nothing
       }
           
            }
            
        }
       }
        
        
    }//GEN-LAST:event_facultypapersjComboBoxPopupMenuWillBecomeInvisible
  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facultyInforUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facultyInforUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facultyInforUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facultyInforUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int ID =1;
                new facultyInforUI(ID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> currentStudentjComboBox;
    private javax.swing.JLabel currentStudentjLabel;
    private javax.swing.JTextField facultyEmailjTextField;
    private javax.swing.JPanel facultyInfojPanel;
    private javax.swing.JLabel facultyPaperAbstractjLabel;
    private javax.swing.JTextArea facultyPaperAbstractjTextArea;
    private javax.swing.JLabel facultyPaperCitationjLabel;
    private javax.swing.JTextArea facultyPaperCitationjTextArea;
    private javax.swing.JLabel facultyPaperTitlejLabel;
    private javax.swing.JLabel facultyPapersComboboxjLabel;
    private javax.swing.JPanel facultyPapersjPanel;
    private javax.swing.JTextField facultynamejTextField;
    private javax.swing.JTextArea facultypaperTitlejTextArea;
    private javax.swing.JComboBox<String> facultypapersjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea lookingForStudentjjTextArea;
    private javax.swing.JLabel lookingForstudentjLabel;
    // End of variables declaration//GEN-END:variables
}
