/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author katie
 */
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.event.*;
import javax.swing.text.*;
public class AdminEdit extends javax.swing.JFrame {

    /**
     * Creates new form FacultyEdit
     */
    String facultyName;
    int facID;
    String firstName;
    String lastName;
    String email;
    String password;
    BLFaculty faculty;
    BLFaculty displayProf;
    ArrayList<String> profList;
    ArrayList<Integer> profIDs;
    String firstNameText;
    String lastNameText;
    String emailText;
    

    
    public AdminEdit() {
        
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        adminEditPanel = new javax.swing.JPanel();
        instructionLabel = new javax.swing.JLabel();
        ArrayList<ArrayList<String>> profs = new ArrayList();
        try {
            profs = faculty.profList();
        }
        catch(DLException e){
            //blah
        }
        profList = new ArrayList();
        profIDs = new ArrayList();
        profList.add("");  //should be a blank option first
        profList.add("Add New Faculty"); //Add option for new paper to combo box list
        for(int i = 0; i < profs.size(); i++)
        {
            profList.add(profs.get(i).get(1));
            profIDs.add(Integer.parseInt(profs.get(i).get(0)));
        }
        facultyList = new javax.swing.JComboBox();
        facultyInfoPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addNewFacultyButton = new javax.swing.JButton();
        saveChangesButton = new javax.swing.JButton();
        returnToSearchButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        adminEditPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Faculty Information"));
        adminEditPanel.setPreferredSize(new java.awt.Dimension(612, 489));

        instructionLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        instructionLabel.setText("Select faculty member");

        facultyList.setModel(new javax.swing.DefaultComboBoxModel(profList.toArray()));
        facultyList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyListActionPerformed(evt);
            }
        });

        facultyInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Faculty Information"));

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        emailLabel.setText("Email");

        firstNameTextField.setEditable(false);

        emailTextField.setEditable(false);

        lastNameTextField.setEditable(false);

        javax.swing.GroupLayout facultyInfoPanelLayout = new javax.swing.GroupLayout(facultyInfoPanel);
        facultyInfoPanel.setLayout(facultyInfoPanelLayout);
        facultyInfoPanelLayout.setHorizontalGroup(
            facultyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyInfoPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(facultyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(emailLabel)
                    .addComponent(lastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(facultyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );
        facultyInfoPanelLayout.setVerticalGroup(
            facultyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyInfoPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(facultyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(facultyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(facultyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        firstNameTextField.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent evt) {
                firstNameTextFieldDocumentUpdated(evt);
            }
            public void removeUpdate(DocumentEvent evt) {
                firstNameTextFieldDocumentUpdated(evt);
            }
            public void changedUpdate(DocumentEvent evt) {
                firstNameTextFieldDocumentUpdated(evt);
            }
        });
        emailTextField.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent evt) {
                emailTextFieldDocumentUpdated(evt);
            }
            public void removeUpdate(DocumentEvent evt) {
                emailTextFieldDocumentUpdated(evt);
            }
            public void changedUpdate(DocumentEvent evt) {
                emailTextFieldDocumentUpdated(evt);
            }
        });
        lastNameTextField.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent evt) {
                lastNameTextFieldDocumentUpdated(evt);
            }
            public void removeUpdate(DocumentEvent evt) {
                lastNameTextFieldDocumentUpdated(evt);
            }
            public void changedUpdate(DocumentEvent evt) {
                lastNameTextFieldDocumentUpdated(evt);
            }
        });

        editButton.setText("Edit Faculty");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Faculty");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addNewFacultyButton.setText("Add New Faculty");
        addNewFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewFacultyButtonActionPerformed(evt);
            }
        });

        saveChangesButton.setText("Save Changes");
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        returnToSearchButton.setText("Return to Search");
        returnToSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminEditPanelLayout = new javax.swing.GroupLayout(adminEditPanel);
        adminEditPanel.setLayout(adminEditPanelLayout);
        adminEditPanelLayout.setHorizontalGroup(
            adminEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminEditPanelLayout.createSequentialGroup()
                        .addGroup(adminEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(adminEditPanelLayout.createSequentialGroup()
                                .addComponent(editButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton))
                            .addComponent(instructionLabel)
                            .addComponent(facultyList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(adminEditPanelLayout.createSequentialGroup()
                        .addComponent(addNewFacultyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveChangesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnToSearchButton)
                        .addGap(40, 40, 40))
                    .addGroup(adminEditPanelLayout.createSequentialGroup()
                        .addComponent(facultyInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        adminEditPanelLayout.setVerticalGroup(
            adminEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminEditPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(instructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(facultyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(adminEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addGap(38, 38, 38)
                .addComponent(facultyInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(adminEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewFacultyButton)
                    .addComponent(saveChangesButton)
                    .addComponent(returnToSearchButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        instructionLabel.getAccessibleContext().setAccessibleName("Select Faculty User");
        facultyInfoPanel.getAccessibleContext().setAccessibleName("Faculty Information");
        facultyInfoPanel.getAccessibleContext().setAccessibleParent(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultyListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyListActionPerformed
        int profListIdx = facultyList.getSelectedIndex();
        if(profListIdx == 1){
            firstNameTextField.setText("");
            lastNameTextField.setText("");
            emailTextField.setText("");
            firstNameTextField.setEditable(true);
            lastNameTextField.setEditable(true);
            emailTextField.setEditable(true);
        }
        else
        {
            int profId = profIDs.get(profListIdx-2);
            displayProf = new BLFaculty(profId);
            try{
                displayProf.fetch();
            }
            catch(DLException e){

            }
            firstNameTextField.setEditable(false);
            lastNameTextField.setEditable(false);
            emailTextField.setEditable(false);
            firstName = displayProf.getFN();
            lastName = displayProf.getLN();
            email = displayProf.getEmail();
            password = displayProf.getPass();

            firstNameTextField.setText(firstName);
            firstNameTextField.setCaretPosition(0);
            lastNameTextField.setText(lastName);
            lastNameTextField.setCaretPosition(0);
            emailTextField.setText(email);
            emailTextField.setCaretPosition(0);

        }
    }//GEN-LAST:event_facultyListActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int profListIdx = facultyList.getSelectedIndex();
        int profID = profIDs.get(profListIdx-2);
        BLFaculty delFaculty = new BLFaculty(profID);
        Object[] options = { "OK", "CANCEL" };
        int question = JOptionPane.showOptionDialog(null, "Click OK to delete faculty", "Warning",JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if(question == JOptionPane.YES_OPTION)
        {
            try{
                delFaculty.delete();
                profIDs.remove(profListIdx-2);
                profList.remove(profListIdx);
                facultyList.setModel(new javax.swing.DefaultComboBoxModel(profList.toArray()));
                firstNameTextField.setText("");
                lastNameTextField.setText("");
                emailTextField.setText("");
                JOptionPane.showMessageDialog(null, "Faculty Deleted");

               }
            catch(DLException e){
                JOptionPane.showMessageDialog(null, "Could not complete operation. Details written to log file.");
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        int profListIdx = facultyList.getSelectedIndex();
        int profID = profIDs.get(profListIdx-2);
        try{
            BLFaculty updateFaculty = new BLFaculty(profID);
            updateFaculty.setUpdateDetails(firstNameText, lastNameText, emailText);
            updateFaculty.put();
            updateFaculty.fetch();
            
            String name = firstNameText + " " + lastNameText;

            profList.set(profListIdx, name);

            facultyList.setModel(new javax.swing.DefaultComboBoxModel(profList.toArray()));
             
            JOptionPane.showMessageDialog(null, "Faculty saved.");

        }
        catch(DLException d){
            JOptionPane.showMessageDialog(null, "Could not complete operation. Details written to log file.");
        }
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void returnToSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToSearchButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_returnToSearchButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        firstNameTextField.setEditable(true);
        lastNameTextField.setEditable(true);
        emailTextField.setEditable(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void addNewFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewFacultyButtonActionPerformed
        int profListIdx = facultyList.getSelectedIndex();
        if(profListIdx == 1){
            try{
                BLFaculty newFaculty = new BLFaculty();
                int newID = newFaculty.setInsertDetails(firstNameText, lastNameText, emailText);
                newFaculty.fetch();
                profIDs.add(newID);
                String name = firstNameText + " " + lastNameText;
                
                profList.add(name);

                facultyList.setModel(new javax.swing.DefaultComboBoxModel(profList.toArray()));
                firstNameTextField.setText("");
                lastNameTextField.setText("");
                emailTextField.setText("");
                JOptionPane.showMessageDialog(null, "Faculty added.");
                
            }
            catch(DLException d){
                JOptionPane.showMessageDialog(null, "Could not complete operation. Details written to log file.");
            }
        }
    }//GEN-LAST:event_addNewFacultyButtonActionPerformed

        
        private void firstNameTextFieldDocumentUpdated(DocumentEvent evt) {
		Document firstNameTextFieldDocument = (Document)evt.getDocument();
		int firstNameTextFieldLength = firstNameTextFieldDocument.getLength();
		try {
			firstNameText = firstNameTextFieldDocument.getText(0, firstNameTextFieldLength);
		}
		catch (BadLocationException e) {}
	}
        
        
        private void lastNameTextFieldDocumentUpdated(DocumentEvent evt) {
		Document lastNameTextFieldDocument = (Document)evt.getDocument();
		int lastNameTextFieldLength = lastNameTextFieldDocument.getLength();
		try {
			lastNameText = lastNameTextFieldDocument.getText(0, lastNameTextFieldLength);
		}
		catch (BadLocationException e) {}
	}
        
        private void emailTextFieldDocumentUpdated(DocumentEvent evt) {
		Document emailTextFieldDocument = (Document)evt.getDocument();
		int emailTextFieldLength = emailTextFieldDocument.getLength();
		try {
			emailText = emailTextFieldDocument.getText(0, emailTextFieldLength);
		}
		catch (BadLocationException e) {}
	}
        
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewFacultyButton;
    private javax.swing.JPanel adminEditPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel facultyInfoPanel;
    private javax.swing.JComboBox facultyList;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton returnToSearchButton;
    private javax.swing.JButton saveChangesButton;
    // End of variables declaration//GEN-END:variables
}
