
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Group 2: Katherine Shaw, Nazar Al-Wattar,Fahad Alotaibi , Chris Penepent
 */
public class facultyInforUI extends javax.swing.JFrame {

    private ArrayList<ArrayList<String>> currentStudent;
    private ArrayList<ArrayList<String>> profPapers;
    public  BLPaper myPaper;
    public   BLFaculty bL;
      
    /**
     * Constructor
     * 
     */
    public facultyInforUI()
    {
    
    }
    
    /**
     * ID Constructor
     * 
     * @param ID
     * @throws DLException
     */
    public facultyInforUI(int ID) throws DLException {
        
         bL = new BLFaculty(ID);
       
        try{
           
            bL.fetch();
         
                     
        }catch(DLException e)
        {
       throw new DLException(e, "Unix time: " + String.valueOf(System.currentTimeMillis()/1000), "Error In the ID facultyInforUI Constructor");
        
        }
       
        
       
                
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultyInfojPanel = new javax.swing.JPanel();
        facultyPapersjPanel = new javax.swing.JPanel();
        //Get papersList

        try {

            MySQLDatabase msdb = MySQLDatabase.getInstance();
            msdb.connect();
            bL.fetch();
            this.profPapers = bL.profPapersList();
        }
        catch(DLException e){
            Logger.getLogger(facultyInforUI.class.getName()).log(Level.SEVERE, null, e);
        }

        String[] profPapersTitle = new String[this.profPapers.size()+1];

        profPapersTitle[0] = "<click here to select paper>";
        for (int i=1;i<profPapersTitle.length;i++) {
            profPapersTitle[i] = this.profPapers.get(i-1).get(1);
        }
        facultypapersjComboBox = new javax.swing.JComboBox<>(profPapersTitle);
        facultyPapersComboboxjLabel = new javax.swing.JLabel();
        facultyPaperTitlejLabel = new javax.swing.JLabel();
        facultyPaperAbstractjLabel = new javax.swing.JLabel();
        facultyPaperCitationjLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        facultyPaperAbstractjTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        facultypaperTitlejTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        facultyPaperCitationjTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        //Current Studen(s) Name

        try {
            MySQLDatabase msdb = MySQLDatabase.getInstance();
            msdb.connect();

            this.currentStudent = bL.profCurrentStudentList();
        }
        catch(DLException e){
            Logger.getLogger(facultyInforUI.class.getName()).log(Level.SEVERE, null, e);
        }

        String[] profStudentNames = new String[this.currentStudent.size()+1];
        profStudentNames[0] = "";
        for (int i=1;i<profStudentNames.length;i++) {
            profStudentNames[i] = this.currentStudent.get(i-1).get(0);

        }
        currentStudentjComboBox = new javax.swing.JComboBox<>(profStudentNames);
        currentStudentjLabel = new javax.swing.JLabel();
        lookingForstudentjLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lookingForStudentjjTextArea = new javax.swing.JTextArea(bL.askHelp);
        try{
            bL.fetch();

        }catch(DLException e)
        {
            //Do nothing

        }
        facultyFullNamejLabel = new javax.swing.JLabel(bL.firstName + " " + bL.lastName);
        facultyEmailjLabel = new javax.swing.JLabel(bL.email);
        returnToSearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        facultyInfojPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professor Information Page", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        facultyInfojPanel.setName(""); // NOI18N

        facultyPapersjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professor Papers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 15))); // NOI18N
        facultyPapersjPanel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        facultyPapersjPanel.setName("Professor Papers"); // NOI18N

        facultypapersjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(profPapersTitle));
        facultypapersjComboBox.setSelectedIndex(0);
        facultypapersjComboBox.setSelectedItem(facultypapersjComboBox);
        facultypapersjComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                facultypapersjComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        facultyPapersComboboxjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        facultyPapersComboboxjLabel.setText("Papers");

        facultyPaperTitlejLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        facultyPaperTitlejLabel.setText("Title");

        facultyPaperAbstractjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        facultyPaperAbstractjLabel.setText("Abstract");

        facultyPaperCitationjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        facultyPaperCitationjLabel.setText("Citation");

        facultyPaperAbstractjTextArea.setEnabled(false);
        facultyPaperAbstractjTextArea.setColumns(20);
        facultyPaperAbstractjTextArea.setRows(5);
        facultyPaperAbstractjTextArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(facultyPaperAbstractjTextArea);

        facultypaperTitlejTextArea.setEnabled(false);
        facultypaperTitlejTextArea.setColumns(20);
        facultypaperTitlejTextArea.setRows(5);
        facultypaperTitlejTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(facultypaperTitlejTextArea);

        facultyPaperCitationjTextArea.setEnabled(false);
        facultyPaperCitationjTextArea.setColumns(20);
        facultyPaperCitationjTextArea.setRows(5);
        facultyPaperCitationjTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(facultyPaperCitationjTextArea);

        javax.swing.GroupLayout facultyPapersjPanelLayout = new javax.swing.GroupLayout(facultyPapersjPanel);
        facultyPapersjPanel.setLayout(facultyPapersjPanelLayout);
        facultyPapersjPanelLayout.setHorizontalGroup(
            facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(facultyPaperAbstractjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(facultyPaperTitlejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(facultyPaperCitationjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(facultyPapersComboboxjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addComponent(facultypapersjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        facultyPapersjPanelLayout.setVerticalGroup(
            facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultypapersjComboBox)
                    .addComponent(facultyPapersComboboxjLabel))
                .addGap(17, 17, 17)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyPaperTitlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(facultyPaperAbstractjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyPapersjPanelLayout.createSequentialGroup()
                        .addComponent(facultyPaperCitationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Professor Name");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Professor Email");

        currentStudentjComboBox.setSelectedIndex(1);
        currentStudentjComboBox.setSelectedItem(currentStudentjComboBox);

        currentStudentjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        currentStudentjLabel.setText("Current Student (s) Name");

        lookingForstudentjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lookingForstudentjLabel.setText("Looking for a student researcher in");

        lookingForStudentjjTextArea.setColumns(20);
        lookingForStudentjjTextArea.setRows(5);
        lookingForStudentjjTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(lookingForStudentjjTextArea);
        if(lookingForStudentjjTextArea.getText().equals(""))
        lookingForStudentjjTextArea.setEnabled(false);
        else
        lookingForStudentjjTextArea.setEnabled(true);

        returnToSearchButton.setText("Return to Search Window");
        returnToSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout facultyInfojPanelLayout = new javax.swing.GroupLayout(facultyInfojPanel);
        facultyInfojPanel.setLayout(facultyInfojPanelLayout);
        facultyInfojPanelLayout.setHorizontalGroup(
            facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyInfojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                        .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentStudentjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lookingForstudentjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(currentStudentjComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(returnToSearchButton)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facultyPapersjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(facultyEmailjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(facultyFullNamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63)))
                .addContainerGap())
        );
        facultyInfojPanelLayout.setVerticalGroup(
            facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyFullNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facultyEmailjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                        .addComponent(facultyPapersjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                        .addComponent(currentStudentjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(currentStudentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(lookingForstudentjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnToSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(facultyInfojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(facultyInfojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        facultyInfojPanel.getAccessibleContext().setAccessibleName("Faculty Information Page");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void facultypapersjComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_facultypapersjComboBoxPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        
        
        
         if(facultypapersjComboBox.getSelectedIndex()>0)
        {
            
        int index = facultypapersjComboBox.getSelectedIndex();
           String item = facultypapersjComboBox.getSelectedItem().toString();
                      
            for(int i=0; i<profPapers.size(); i++)
            {
            if(profPapers.get(i).get(1).equals(item))
            {
          int  paperIndex =Integer.parseInt(profPapers.get(i).get(0));
                             
                MySQLDatabase msdb = MySQLDatabase.getInstance();
                try {
                    msdb.connect();
                }catch(DLException e)
                {
                 Logger.getLogger(facultyInforUI.class.getName()).log(Level.SEVERE, null, e);
                }
               
              
                
                myPaper = new BLPaper(paperIndex);
                try {
                    myPaper.fetch();  
                    
                  
                    
                    facultypaperTitlejTextArea = new javax.swing.JTextArea(myPaper.title);
                    facultypaperTitlejTextArea.setColumns(20);
                    facultypaperTitlejTextArea.setRows(5);
                   
                    jScrollPane1.setViewportView(facultypaperTitlejTextArea);
                   facultyPaperAbstractjTextArea = new javax.swing.JTextArea(myPaper.pAbstract);
                   facultyPaperAbstractjTextArea.setColumns(20);
                   facultyPaperAbstractjTextArea.setRows(5);
                   jScrollPane3.setViewportView(facultyPaperAbstractjTextArea);
                   facultyPaperAbstractjTextArea.setLineWrap(true);
                   facultyPaperAbstractjTextArea.setWrapStyleWord(true);
                   facultyPaperCitationjTextArea = new javax.swing.JTextArea(myPaper.citation);
                    facultyPaperCitationjTextArea.setColumns(20);
                    facultyPaperCitationjTextArea.setRows(5);
                    jScrollPane4.setViewportView(facultyPaperCitationjTextArea);
                    
                   
            
            }catch (DLException ex) {
            Logger.getLogger(facultyInforUI.class.getName()).log(Level.SEVERE, null, ex);
       }
           
            }
            
        }
       }
        
        
    }//GEN-LAST:event_facultypapersjComboBoxPopupMenuWillBecomeInvisible

    private void returnToSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToSearchButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_returnToSearchButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> currentStudentjComboBox;
    private javax.swing.JLabel currentStudentjLabel;
    private javax.swing.JLabel facultyEmailjLabel;
    private javax.swing.JLabel facultyFullNamejLabel;
    private javax.swing.JPanel facultyInfojPanel;
    private javax.swing.JLabel facultyPaperAbstractjLabel;
    private javax.swing.JTextArea facultyPaperAbstractjTextArea;
    private javax.swing.JLabel facultyPaperCitationjLabel;
    private javax.swing.JTextArea facultyPaperCitationjTextArea;
    private javax.swing.JLabel facultyPaperTitlejLabel;
    private javax.swing.JLabel facultyPapersComboboxjLabel;
    private javax.swing.JPanel facultyPapersjPanel;
    private javax.swing.JTextArea facultypaperTitlejTextArea;
    private javax.swing.JComboBox<String> facultypapersjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea lookingForStudentjjTextArea;
    private javax.swing.JLabel lookingForstudentjLabel;
    private javax.swing.JButton returnToSearchButton;
    // End of variables declaration//GEN-END:variables
}
