/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author katie
 */
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.event.*;
import javax.swing.text.*;
public class FacultyEdit extends javax.swing.JFrame {

    /**
     * Creates new form FacultyEdit
     */
    public FacultyEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultyEditPanel = new javax.swing.JPanel();
        profNameLabel = new javax.swing.JLabel();
        facultyPapersList = new javax.swing.JComboBox();
        paperInfoPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        abstractLabel = new javax.swing.JLabel();
        citationLabel = new javax.swing.JLabel();
        keywordLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        abstractTextArea = new javax.swing.JTextArea();
        citationTextField = new javax.swing.JTextField();
        keywordsTextField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addNewPaperButton = new javax.swing.JButton();
        saveChangesButton = new javax.swing.JButton();
        returnToSearchButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        studentNameTextBox = new javax.swing.JTextField();
        needStudentLabel = new javax.swing.JLabel();
        needStudentTextBox = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        facultyEditPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Faculty Information"));
        facultyEditPanel.setPreferredSize(new java.awt.Dimension(612, 489));

        profNameLabel.setText("Professor Name");

        facultyPapersList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        facultyPapersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyPapersListActionPerformed(evt);
            }
        });

        paperInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Paper Information"));

        titleLabel.setText("Title");

        abstractLabel.setText("Abstract");

        citationLabel.setText("Citation");

        keywordLabel.setText("Keywords");

        jLabel1.setText("(Separate with commas)");

        titleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextFieldActionPerformed(evt);
            }
        });

        abstractTextArea.setColumns(20);
        abstractTextArea.setRows(5);
        jScrollPane1.setViewportView(abstractTextArea);

        javax.swing.GroupLayout paperInfoPanelLayout = new javax.swing.GroupLayout(paperInfoPanel);
        paperInfoPanel.setLayout(paperInfoPanelLayout);
        paperInfoPanelLayout.setHorizontalGroup(
            paperInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paperInfoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(paperInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paperInfoPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(37, 37, 37)
                        .addComponent(titleTextField))
                    .addGroup(paperInfoPanelLayout.createSequentialGroup()
                        .addComponent(citationLabel)
                        .addGap(18, 18, 18)
                        .addComponent(citationTextField))
                    .addGroup(paperInfoPanelLayout.createSequentialGroup()
                        .addComponent(abstractLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                    .addGroup(paperInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(paperInfoPanelLayout.createSequentialGroup()
                        .addComponent(keywordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keywordsTextField)))
                .addContainerGap())
        );
        paperInfoPanelLayout.setVerticalGroup(
            paperInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paperInfoPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(paperInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paperInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abstractLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(paperInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(citationLabel)
                    .addComponent(citationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paperInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywordLabel)
                    .addComponent(keywordsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        editButton.setText("Edit Paper");

        jButton1.setText("Delete Paper");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addNewPaperButton.setText("Add New Paper");

        saveChangesButton.setText("Save Changes");
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        returnToSearchButton.setText("Return to Search");
        returnToSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToSearchButtonActionPerformed(evt);
            }
        });

        addStudentButton.setText("Add Student");
        addStudentButton.setEnabled(false);
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        studentNameTextBox.setText("<student name>");
        studentNameTextBox.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent evt) {
                studentNameTextBoxDocumentUpdated(evt);
            }
            public void removeUpdate(DocumentEvent evt) {
                studentNameTextBoxDocumentUpdated(evt);
            }
            public void changedUpdate(DocumentEvent evt) {
                studentNameTextBoxDocumentUpdated(evt);
            }
        });
        studentNameTextBox.setRequestFocusEnabled(false);
        studentNameTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentNameTextBoxFocusGained(evt);
            }
        });

        needStudentLabel.setText("Student Researcher Text");

        needStudentTextBox.setCaretPosition(0);
        needStudentTextBox.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent evt) {
                needStudentTextBoxDocumentUpdated(evt);
            }
            public void removeUpdate(DocumentEvent evt) {
                needStudentTextBoxDocumentUpdated(evt);
            }
            public void changedUpdate(DocumentEvent evt) {
                needStudentTextBoxDocumentUpdated(evt);
            }
        });

        jButton3.setText("Update");

        javax.swing.GroupLayout facultyEditPanelLayout = new javax.swing.GroupLayout(facultyEditPanel);
        facultyEditPanel.setLayout(facultyEditPanelLayout);
        facultyEditPanelLayout.setHorizontalGroup(
            facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facultyEditPanelLayout.createSequentialGroup()
                        .addGroup(facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(facultyEditPanelLayout.createSequentialGroup()
                                .addComponent(editButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletePaperButton))
                            .addComponent(profNameLabel)
                            .addComponent(facultyPapersList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(facultyEditPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(needStudentLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(needStudentTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyEditPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(facultyEditPanelLayout.createSequentialGroup()
                        .addGroup(facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paperInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profNameLabel))
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addGroup(facultyEditPanelLayout.createSequentialGroup()
                        .addComponent(addNewPaperButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveChangesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnToSearchButton)))
                .addContainerGap())
        );
        facultyEditPanelLayout.setVerticalGroup(
            facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyEditPanelLayout.createSequentialGroup()
                .addGroup(facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(facultyEditPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(facultyPapersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editButton)
                            .addComponent(jButton1)))
                    .addGroup(facultyEditPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(profNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(studentNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(needStudentTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(needStudentLabel)
                            .addComponent(updateButton))))
                .addComponent(paperInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewPaperButton)
                    .addComponent(saveChangesButton)
                    .addComponent(returnToSearchButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(facultyEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(facultyEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultyPapersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyPapersListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyPapersListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void titleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextFieldActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void returnToSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToSearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnToSearchButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        try{
            faculty.addStudent(studentName);
        }
        catch(DLException e){
            JOptionPane.showMessageDialog(null, "Could not complete operation. Details written to log file.");
        }
		JOptionPane.showMessageDialog(null, "Student added.");
		studentNameTextBox.setText("");
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try{
            faculty.needHelp(helpText);
        }
        catch(DLException e){
            //
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        titleTextArea.setEditable(true);
        abstractTextArea.setEditable(true);
        citationTextArea.setEditable(true);
        keywordsTextField.setEditable(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void studentNameTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentNameTextBoxFocusGained
        javax.swing.JTextField tf = (javax.swing.JTextField)evt.getSource();
		if (tf.getText().equals("<student name>")) {
			studentNameTextBox.setText("");
		}
    }//GEN-LAST:event_studentNameTextBoxFocusGained

	private void studentNameTextBoxDocumentUpdated(DocumentEvent evt) {
		Document studentNameTextBoxDocument = (Document)evt.getDocument();
		if (studentNameTextBoxDocument.getLength() > 0) {
			this.addStudentButton.setEnabled(true);
		}
		else {
			this.addStudentButton.setEnabled(false);
		}
		int studentNameLength = studentNameTextBoxDocument.getLength();
		try {
			studentName = studentNameTextBoxDocument.getText(0, studentNameLength);
		}
		catch (BadLocationException e) {}
	}
	
	private void needStudentTextBoxDocumentUpdated(DocumentEvent evt) {
		Document needStudentTextBoxDocument = (Document)evt.getDocument();
		int needHelpLength = needStudentTextBoxDocument.getLength();
		try {
			helpText = needStudentTextBoxDocument.getText(0, needHelpLength);
		}
		catch (BadLocationException e) {}
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abstractLabel;
    private javax.swing.JTextArea abstractTextArea;
    private javax.swing.JButton addNewPaperButton;
    private javax.swing.JLabel citationLabel;
    private javax.swing.JTextField citationTextField;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel facultyEditPanel;
    private javax.swing.JComboBox facultyPapersList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JTextField keywordsTextField;
    private javax.swing.JLabel needStudentLabel;
    private javax.swing.JTextField needStudentTextBox;
    private javax.swing.JPanel paperInfoPanel;
    private javax.swing.JLabel profNameLabel;
    private javax.swing.JButton returnToSearchButton;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JTextField studentNameTextBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
