
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NAZAR ALWATTAR
 */
public class facultyInforUI extends javax.swing.JFrame {

    private ArrayList<ArrayList<String>> currentStudent;
    private ArrayList<ArrayList<String>> profPapers;
    /**
     * Creates new form facultyInforUI
     */
    public facultyInforUI() {
        int ID = 2;
        BLFaculty bL = new BLFaculty(ID);
       
        try{
            bL.fetch();
                       
                facultynamejTextField.setText(bL.firstName + "" + bL.lastName);
                facultyEmailjTextField.setText(bL.email);
                lookingForStudentjTextField.setText(bL.askHelp);
              
        }catch(DLException e)
        {
        //Do nothing
        
        }
                initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultyInfojPanel = new javax.swing.JPanel();
        facultyPapersjPanel = new javax.swing.JPanel();
        facultypapersjComboBox = new javax.swing.JComboBox<>();
        facultypaperTitlejTextField = new javax.swing.JTextField();
        facultyPaperAbstractjTextField = new javax.swing.JTextField();
        facultyPaperCitationjTextField = new javax.swing.JTextField();
        facultyPapersComboboxjLabel = new javax.swing.JLabel();
        facultyPaperTitlejLabel = new javax.swing.JLabel();
        facultyPaperAbstractjLabel = new javax.swing.JLabel();
        facultyPaperCitationjLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        facultynamejTextField = new javax.swing.JTextField();
        facultyEmailjTextField = new javax.swing.JTextField();
        currentStudentjComboBox = new javax.swing.JComboBox<>();
        currentStudentjLabel = new javax.swing.JLabel();
        lookingForStudentjTextField = new javax.swing.JTextField();
        lookingForstudentjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        facultyInfojPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Professor Information Page"));
        facultyInfojPanel.setName(""); // NOI18N

        facultyPapersjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Professor Papers"));
        facultyPapersjPanel.setName("Professor Papers"); // NOI18N

        facultypapersjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        facultyPapersComboboxjLabel.setText("Papers");

        facultyPaperTitlejLabel.setText("Title");

        facultyPaperAbstractjLabel.setText("Abstract");

        facultyPaperCitationjLabel.setText("Citation");

        javax.swing.GroupLayout facultyPapersjPanelLayout = new javax.swing.GroupLayout(facultyPapersjPanel);
        facultyPapersjPanel.setLayout(facultyPapersjPanelLayout);
        facultyPapersjPanelLayout.setHorizontalGroup(
            facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(facultyPapersComboboxjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyPaperCitationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyPaperAbstractjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(facultyPaperTitlejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(facultyPaperAbstractjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facultyPaperCitationjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facultypaperTitlejTextField)
                    .addComponent(facultypapersjComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 423, Short.MAX_VALUE))
                .addContainerGap())
        );
        facultyPapersjPanelLayout.setVerticalGroup(
            facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(facultypapersjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyPapersComboboxjLabel))
                .addGap(29, 29, 29)
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(facultypaperTitlejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(facultyPaperTitlejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facultyPapersjPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(facultyPaperAbstractjTextField)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyPapersjPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(facultyPaperAbstractjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(facultyPapersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyPaperCitationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyPaperCitationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setText("Professor Name");

        jLabel2.setText("Professor Email");

        currentStudentjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        currentStudentjLabel.setText("Current Student (s) Name");

        lookingForstudentjLabel.setText("Looking for a student researcher in");

        javax.swing.GroupLayout facultyInfojPanelLayout = new javax.swing.GroupLayout(facultyInfojPanel);
        facultyInfojPanel.setLayout(facultyInfojPanelLayout);
        facultyInfojPanelLayout.setHorizontalGroup(
            facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyInfojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facultyEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facultynamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                        .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentStudentjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                                .addComponent(lookingForstudentjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 47, Short.MAX_VALUE))
                            .addComponent(lookingForStudentjTextField)
                            .addComponent(currentStudentjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(facultyPapersjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        facultyInfojPanelLayout.setVerticalGroup(
            facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyInfojPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultynamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(facultyInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facultyInfojPanelLayout.createSequentialGroup()
                        .addComponent(currentStudentjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(currentStudentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(lookingForstudentjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lookingForStudentjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(facultyPapersjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(facultyInfojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(facultyInfojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        facultyInfojPanel.getAccessibleContext().setAccessibleName("Faculty Information Page");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facultyInforUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facultyInforUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facultyInforUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facultyInforUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facultyInforUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> currentStudentjComboBox;
    private javax.swing.JLabel currentStudentjLabel;
    private javax.swing.JTextField facultyEmailjTextField;
    private javax.swing.JPanel facultyInfojPanel;
    private javax.swing.JLabel facultyPaperAbstractjLabel;
    private javax.swing.JTextField facultyPaperAbstractjTextField;
    private javax.swing.JLabel facultyPaperCitationjLabel;
    private javax.swing.JTextField facultyPaperCitationjTextField;
    private javax.swing.JLabel facultyPaperTitlejLabel;
    private javax.swing.JLabel facultyPapersComboboxjLabel;
    private javax.swing.JPanel facultyPapersjPanel;
    private javax.swing.JTextField facultynamejTextField;
    private javax.swing.JTextField facultypaperTitlejTextField;
    private javax.swing.JComboBox<String> facultypapersjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField lookingForStudentjTextField;
    private javax.swing.JLabel lookingForstudentjLabel;
    // End of variables declaration//GEN-END:variables
}
